version: "2"

services:
  base:
    image: node:14.15.4
    working_dir: /usr/src/service
    volumes:
      - .:/usr/src/service
    labels:
      - "com.coursecamp.description=development"
      - "com.coursecamp.container=builder"
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build
volumes:
  nodemodules:
    external: "true"
